name: Deploy Ng

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run npm install
      run: npm install -y
    - name: Build things
      run: npm run build
    - name: Deploy things
      run: npm run deploy
